spring:
  cloud:
    nacos:
      server-addr: 106.15.5.247:8848
      config:
        group: SSS_GROUP
  config:
    import:
      - nacos:dev.yml?refreshEnabled=true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl