server:
  port: 9030 # port

spring:
  application:
    name: rms # 服务名
  profiles:
    active: dev #默认为开发环境 -> application-dev.yml / prod
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml # 映射文件目录
    - classpath*:com/**/mapper-mbg/*.xml # 不但扫描当前JAR，扫描所有JAR,主要作用：扫描其它地方的mapper
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志
