spring:
  application:
    name: sss-security # 服务名
  profiles:
    active: dev #默认为开发环境 -> application-dev.yml / prod

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml # 映射文件目录
    - classpath*:com/**/mapper/*.xml # 不但扫描当前JAR，扫描所有JAR,主要作用：扫描mbg代码生成器的mapper