jwt:
  tokenKey: Authorization #JWT存储的请求头
  secret: sss-security-secret #JWT加解密使用的密钥

login:
  expiration: 604800 #登录过期时间(token过期时间)(60*60*24*7)

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /test/**